name := "helloworld"

version := "0.1"

scalaVersion := "2.10.2"

liftInfoSettings

sourceGenerators in Compile <+= liftInfo

liftInfoKeys := Seq(name, version)

liftInfoPackage := "hello"

homepage := Some(url("http://example.com"))

licenses := Seq("MIT License" -> url("https://github.com/sbt/sbt-liftinfo/blob/master/LICENSE"))

TaskKey[Unit]("check") <<= (sourceManaged in Compile) map { (dir) =>
  val f = dir / "sbt-liftinfo" / ("%s.scala" format "LiftInfo")
  val lines = scala.io.Source.fromFile(f).getLines.toList
  lines match {
    case """package hello""" ::
         """""" ::
         """/** This object was generated by sbt-liftinfo. */""" ::
         """case object LiftInfo {""" ::
         """  /** The value is "helloworld". */""" ::
         """  val name = "helloworld"""" ::
         """  /** The value is "0.1". */""" ::
         """  val version = "0.1"""" ::
         """  override val toString = "name: %s, version: %s" format (name, version)""" ::
         "" ::
         """  val toMap = Map[String, Any](""" ::
         """    "name" -> name,""" ::
         """    "version" -> version)""" ::
         """}""" :: Nil =>
    case _ => sys.error("unexpected output: \n" + lines.mkString("\n"))
  }
  ()
}
